[tool.poetry]
name = "fujikawa"
version = "0.1.0"
description = ""
authors = ["fujikawa <fujikawa@example.com>"]
readme = "README.md"
packages = [
    {include = "app", from = "."}
]

[tool.poetry.dependencies]
python = "^3.12"
sounddevice = "^0.5.2"
numpy = "^2.3.1"
opencv-python = "^4.11.0.86"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
